Added Alerts Component
Krushna-Kulkarni/CascadeUI pull request #2
Opened 2022-02-08 16:48 UTC by Krushna-Kulkarni

2022-02-08 16:58 UTC, AshutoshM29 commented
You should add more variation in alert

2022-02-08 16:59 UTC, Krushna-Kulkarni commented
> You should add more variation in alert

Okay. I will add more variations.

2022-02-08 17:42 UTC, sri-rishi reviewed
Just a suggestion , Likely alerts have text align to left side

2022-02-08 17:45 UTC, sri-rishi requested changes

2022-02-08 17:45 UTC, sri-rishi commented on style.css
> +  background-color: #bbf7d0;
use variables for colors instead  of hex or rgb

2022-02-08 17:57 UTC, AnkitaBagale commented
Hey Krushna,
Please add a description in your PR so that reviewer would understand what is it about.
If PR contains UI changes, add screenshots of the changes as well.

Also use a code formatter e.g. prettier in vscode, to make code cleaner.
Added few comments, please go through it.

2022-02-08 18:14 UTC, AnkitaBagale requested changes

2022-02-08 18:14 UTC, AnkitaBagale commented on index.html
> +    <!-- Header -->
Remove commented code if not necessary

2022-02-08 18:14 UTC, AnkitaBagale commented on index.html
>                  <li><a href="#9">Component</a> </li>
Try to use meaningful ids

2022-02-08 18:14 UTC, AnkitaBagale commented on index.html
>              <section id="1">
Same here, use meaningful id names

2022-02-08 18:14 UTC, AnkitaBagale commented on index.html
> +                    <div class="alerts-child success"><i class="fa fa-check-circle"></i><span class="p-md">Success
It is a single alert component, i would suggest use class name "alert" not "alerts".
Also instead of alerts-child, just using alert suffice.

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +  color: #fff;
use color variable instead

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +.alerts-child.success{
try to write styling on a single class, avoid complex selectors, this will avoid bugs due to specificity, and it's better for debugging in large apps.
e.g. here- add class alert-success instead of success and add style to alert-success instead of .alerts-child.success
```
.alert-success{
  background-color: #bbf7d0;
  color:green;
}
```

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +  background-color: #bfdbfe;
Avoid hard coded colors, use css variables

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +.alerts-container {
If this styling is for document site, write it in a separate file used for docs site.

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +span.p-md{
avoid complex selectors, instead use a class name, here u can create utility class e.g. 
```
.mx-1{
margin: 0 4px
}
```

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +.alerts-code-container{
If this styling is for the document site only, write it in a separate file used for docs site.

2022-02-08 18:14 UTC, AnkitaBagale commented on style.css
> +  grid-gap: 20px;
Avoid using px, use rem

2022-02-09 04:21 UTC, veereshbv04 commented on style.css
> +.alerts-child {
add close button to avatars, it is usually present in alerts

2022-02-09 04:23 UTC, veereshbv04 commented on style.css
> +.alerts-child.info{
for better naming, you should have used alert instead of alerts

2022-02-10 15:17 UTC, merged